# Generated by Django 5.1.4 on 2026-07-20 04:50

from urllib.parse import urlparse

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_repository_relation(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Repository = apps.get_model("projects", "Repository")

    for project in Project.objects.all().iterator():
        if project.repository_id:
            Repository.objects.filter(pk=project.repository_id).update(
                project_id=project.pk
            )
            continue

        if not project.repository_url:
            continue

        parsed = urlparse(project.repository_url)
        path_parts = [part for part in parsed.path.split("/") if part]
        repository_name = (
            path_parts[-1].removesuffix(".git")
            if path_parts
            else parsed.hostname or "repository"
        )
        full_name = (
            "/".join(path_parts[-2:]).removesuffix(".git")
            if len(path_parts) >= 2
            else repository_name
        )
        Repository.objects.create(
            project_id=project.pk,
            name=repository_name[:150],
            full_name=full_name[:300],
            html_url=project.repository_url,
        )

    Repository.objects.filter(project_id__isnull=True).delete()


def restore_project_repository_relation(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Repository = apps.get_model("projects", "Repository")

    for repository in Repository.objects.exclude(project_id=None).iterator():
        Project.objects.filter(pk=repository.project_id).update(
            repository_id=repository.pk,
            repository_url=repository.html_url,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_team_project_one_to_one"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repository",
                to="projects.project",
            ),
        ),
        migrations.RunPython(
            move_repository_relation,
            restore_project_repository_relation,
        ),
        migrations.RemoveField(
            model_name="project",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="project",
            name="repository_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="project",
            name="visibility",
        ),
        migrations.AddField(
            model_name="project",
            name="max_members",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("FINISHED", "Finished"),
                    ("INACTIVE", "Inactive"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="full_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="repository",
            name="refresh_status",
            field=models.CharField(
                blank=True,
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_leader", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DECLINED", "Declined"),
                            ("JOINED", "Joined"),
                            ("LEFT", "Left"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="project_member_status_idx",
                    ),
                    models.Index(
                        fields=["user", "status"],
                        name="user_member_status_idx",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="repository",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repository",
                to="projects.project",
            ),
        ),
    ]
