# Generated by Django 5.1.4 on 2026-07-21 04:50

import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_repository_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('DECLINED', 'Declined'), ('JOINED', 'Joined'), ('LEFT', 'Left')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_members',
            field=models.PositiveIntegerField(default=projects.models.get_default_max_members),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('project', 'id'), name='project_member_project_id_uniq'),
        ),
    ]
