# Generated by Django 5.1.4 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_project_repository_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("id",),
                name="project_member_id_uniq",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE `projects_member` "
                "DROP PRIMARY KEY, "
                "ADD PRIMARY KEY (`project_id`, `id`)"
            ),
            reverse_sql=(
                "ALTER TABLE `projects_member` "
                "DROP PRIMARY KEY, "
                "ADD PRIMARY KEY (`id`)"
            ),
        ),
    ]
