# Generated by Django 5.1.4 on 2026-07-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_member_id_alter_member_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
