# Generated by Django 5.1.4 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_member_composite_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                    ("JOINED", "Joined"),
                    ("LEFT", "Left"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
