# Generated by Django 5.1.4 on 2026-07-21

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_member_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="max_members",
            field=models.PositiveIntegerField(
                default=projects.models.get_default_max_members,
            ),
        ),
    ]
