# Generated by Django 5.1.4 on 2026-07-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_member_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryStatus',
            fields=[
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='projects.repository')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_status_code', models.CharField(max_length=30)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='repository',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='forks',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='language',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_error_code',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='refresh_status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='topics',
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='RepositoryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='projects.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'language'), name='repository_language_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RepositorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pull_requests', models.PositiveIntegerField(default=0)),
                ('commits', models.PositiveIntegerField(default=0)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('has_code_changed', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'date'), name='repository_snapshot_date_uniq')],
            },
        ),
    ]
