# Generated by Django 5.1.4 on 2026-07-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_repositorystatus_repositorylanguage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='forks',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='language',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_error_code',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='refresh_status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='topics',
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
