# Generated by Django 5.1.4 on 2026-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_repository_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorystatus',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
