# Generated by Django 5.1.4 on 2026-08-13 05:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_projectlanguage_remove_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRankingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('stars_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('forks_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commits_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pull_requests_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active_days_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_streak_weight', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRankingWeight',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stars', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commits', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pull_requests', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('active_days', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_streak', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=30)),
                ('stars', models.BigIntegerField()),
                ('forks', models.BigIntegerField()),
                ('commits', models.BigIntegerField()),
                ('pull_requests', models.BigIntegerField()),
                ('active_days', models.PositiveIntegerField()),
                ('max_streak', models.PositiveIntegerField()),
                ('current_streak', models.PositiveIntegerField()),
                ('actual_period_start', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rankings.projectrankingrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'project'), name='ranking_run_project_uniq')],
            },
        ),
    ]
