# Generated by Django 5.1.4 on 2026-08-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_projectlanguage_remove_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRankingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=30)),
                ('stars', models.BigIntegerField()),
                ('forks', models.BigIntegerField()),
                ('commits', models.BigIntegerField()),
                ('pull_requests', models.BigIntegerField()),
                ('actual_period_start', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rankings.projectrankingrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'project'), name='ranking_run_project_uniq')],
            },
        ),
    ]
