# Generated by Django 5.1.4 on 2026-08-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrankingresult',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='projectrankingresult',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='projectrankingresult',
            name='max_streak',
        ),
        migrations.RemoveField(
            model_name='projectrankingrun',
            name='active_days_weight',
        ),
        migrations.RemoveField(
            model_name='projectrankingrun',
            name='max_streak_weight',
        ),
        migrations.RemoveField(
            model_name='projectrankingweight',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='projectrankingweight',
            name='max_streak',
        ),
    ]
