# Generated by Django 5.1.4 on 2026-08-14 07:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRankingWeight',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stars', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commits', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pull_requests', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectranking',
            name='commits_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='projectranking',
            name='forks_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='projectranking',
            name='pull_requests_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='projectranking',
            name='stars_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20),
        ),
    ]
