# Generated by Django 5.1.4 on 2025-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('Photo', models.ImageField(upload_to='')),
                ('on_carousel', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
