# Generated by Django 5.1.4 on 2025-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='issue',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pr',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
