# Generated by Django 5.1.4 on 2026-08-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='stars',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
