# Generated by Django 5.1.4 on 2025-02-11 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_commit_user_issue_user_pr_user_score_user_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='commit',
            new_name='commits',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='issue',
            new_name='issues',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pr',
            new_name='prs',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='star',
            new_name='stars',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField()),
                ('commits', models.IntegerField(default=0)),
                ('prs', models.IntegerField(default=0)),
                ('issues', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity_date')},
            },
        ),
    ]
