# Generated by Django 5.1.4 on 2025-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name_user_student_id_alter_user_github_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
