# Generated by Django 5.1.4 on 2025-01-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
