# Generated by Django 5.1.4 on 2025-02-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_commit_user_commits_rename_issue_user_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='stars',
        ),
    ]
