# Generated by Django 5.1.4 on 2025-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_useractivity_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_date',
            field=models.DateField(null=True),
        ),
    ]
